config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"

  #利用者用
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
}
  get "search" => "searches#search"
  
  devise_scope :user do #ゲストログイン
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  namespace :public do
    #投稿関連
    resources :posts, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
      resource :favorites, only: [:create,:destroy]
      resources :post_comments, only: [:create,:destroy]
    end

    #ユーザー関連
    resources :users, only: [:index,:show,:edit,:update] do
      resource :relationships, only: [:create,:destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      member do #ユーザーidが含まれてるurlを使えるように=>(publiusers/:id/favorites)になる
        get :favorites
      end
    end
    
    # 退会確認画面
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    # 論理削除用のルーティング
    patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'

  end

  #管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
}


  namespace :admin do
    get 'admin' => 'admin#top'
    resources :users, only: [:index, :edit, :update, :show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!, except: [:top]

  def top
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/top.html.erb
<div class="container mt-5 pt-5">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <%= image_tag 'fes.jpg', width: '100%', height: '75%' %>
      <div class="card-img-overlay">
        <p class="text bg-light pt-3 mt-5 mx-auto w-75 center" style="text-align:center;">
          ようこそ、ROCK LIFEへ!!</br>
          このサイトは、バンドやライブ好きの方が、</br>
          好きなバンドやライブの感想を投稿したり、</br>
          ユーザー同士で交流するサイトです。
        </p>
      </div>

      <div class="btn-wrapper col-10 mx-auto mt-5">
        <% if user_signed_in? %>
        <% else %>
        <div class="row">
           <%= link_to 'ゲストログイン', users_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block mb-3 sign_in", method: :post %>
        </div>
        <% end %>
      </div>
      
    </div>
  </div>
</div>