config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"

  #利用者用
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
}
  get "search" => "searches#search"
  
  devise_scope :user do #ゲストログイン
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  namespace :public do
    #投稿関連
    resources :posts, only: [:new,:index,:show,:edit,:create,:destroy,:update] do
      resource :favorites, only: [:create,:destroy]
      resources :post_comments, only: [:create,:destroy]
    end

    #ユーザー関連
    resources :users, only: [:index,:show,:edit,:update] do
      resource :relationships, only: [:create,:destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      member do #ユーザーidが含まれてるurlを使えるように=>(publiusers/:id/favorites)になる
        get :favorites
      end
    end
    
    # 退会確認画面
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    # 論理削除用のルーティング
    patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'

  end

  #管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
}


  namespace :admin do
    get 'admin' => 'admin#top'
    resources :users, only: [:index, :edit, :update, :show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  #フォローした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  #一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50}



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def active_for_authentication? # is_deletedがfalseならtrueを返すようにしている
    super && (is_deleted == false)
  end

  #フォローした時の処理
  def follow(user_id)
    unless self == user_id
      self.relationships.find_or_create_by(followed_id: user_id.to_i, follower_id: self.id)
    end
  end

  #フォローを外す時の処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  #フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all.order("created_at DESC").page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order("created_at DESC").page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "更新しました。"
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :is_deleted)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < ApplicationController
  
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to public_user_path(user), notice: 'guestuserでログインしました。'
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/views/admin/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2 class="mt-5 mb-3" style="border-left: solid 5px #f00; padding: 0.25em 0.5em;">プロフィール</h2>
    <%= form_with model:@user, url:admin_user_path, local:true do |f| %>
    
      <div class="form-group">
        <%= f.label :プロフィール画像 %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      
      <div class="form-group">
        <%= f.label :ユーザー名 %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
      
      <div class="form-group">
        <%= f.label :自己紹介 %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      
      <div class="form-group">
        <%= f.label :会員ステータス %>
        <%= f.radio_button :is_deleted, :false %>
        <%= f.label :is_deleted, "有効" %>
        <%= f.radio_button :is_deleted, :true %>
        <%= f.label :is_deleted, "退会" %>
      </div>
      
      <div class="form-group">
        <%= f.submit "更新する", class: 'btn btn-secondary' %>
      </div>

    <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-8 my-5 mx-auto">
    <h2 class="mb-3" style="border-left: solid 5px #f00; padding: 0.25em 0.5em;">ユーザー</h2>
      <table class='table table-bordered'>
        <thead>
          <tr>
            <th>プロフィール画像</th>
            <th>ユーザー名</th>
            <th>ステータス</th>
            <th>編集</th>
          </tr>
        </thead>
        
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
            <td><%= link_to user.name, admin_user_path(user.id) %></td>
            <td>
              <% if user.is_deleted == false %>
                有効
              <% else %>
                退会済
              <% end %>
            </td>
            <td><%= link_to "編集", edit_admin_user_path(user.id), class: "btn btn-success" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      
      <div class="col-5 mx-auto my-5 pb-5">
        <%= paginate @users, theme: 'twitter-bootstrap-4' %>
      </div>
      
    </div>
  </div>
</div>
    

app/views/admin/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-4 my-5'>
      <h2 class="mb-3" style="border-left: solid 5px #f00; padding: 0.25em 0.5em;">プロフィール</h2>
      <table class='table table-hover'>
        <tr><%= image_tag @user.get_profile_image, size:'100x100' %></tr>
        <tr>
	        <th>ユーザー名</th>
	        <th><%= @user.name %></th>
        </tr>
        <tr>
	        <th>自己紹介</th>
	        <th><%= @user.introduction %></th>
        </tr>
      </table>
      <%= link_to "プロフィール編集", edit_admin_user_path(@user.id), class: "btn btn-success  btn-block" %>
    </div>
    <div class='col-md-8 my-5'>
    <h2 class="ml-3 mb-3" style="border-left: solid 5px #f00; padding: 0.25em 0.5em;">投稿</h2>
      <div class="card-list-container py-5">
      <% @posts.each do |post| %>
        <div class="card w-50 mx-auto mt-4 shadow-lg">
          <%= link_to public_post_path(post.id) do %>
            <%= image_tag post.get_image, class: "card-img-top"; %>
          <% end %>
        <div class="card-body">
          <div class="row">
            <div class="col-3" style="padding-right: 0;">
              <div class="pt-3">
                <%= image_tag post.user.get_profile_image, class: "w-100 rounded-circle", style: "aspect-ratio: 1/1;object-fit: cover;" %>
              </div>
            </div>
             <div class="col-9">
               <p class="card-title">
                 <strong> <i class="far fa-flag"></i><%= post.title %></strong>
               </p>
               <p class="card-text">説明：<%= post.caption %></p>
               <span> By <%= post.user.name %> :</span>
             </div>
            </div>
          </div>
        </div>
      <% end %>
      
      <div class="col-2 mx-auto my-5">
        <%= paginate @posts, theme: 'twitter-bootstrap-4' %>
      </div>
      
      </div>
    </div>
  </div>
</div>